name: Blank
description: Create a new issue from scratch
body:
  - type: markdown
    attributes:
      value: |
        >[!WARNING]
        >If you want to file a bug report, [please use the issue template](https://github.com/readium/swift-toolkit/issues/new?template=bug_report.yml]. If you report a bug with the blank template, your issue will be closed.
  - type: textarea
    id: content
    attributes:
      label: Add a description
      placeholder: Type your description here...
    validations:
      required: true
